name: hci201
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dcdg: ^4.0.1

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - road.png
    - assets/images/
  fonts:
    - family: Neatments
      fonts:
        - asset: assets/fonts/Neatments.otf
          weight: 700

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
